export const PATTERNS = {
  "default": { type: "raw", name: "Default",
    frames: ["⠋","⠙","⠹","⠸","⠼","⠴","⠦","⠧","⠇","⠏"], defaultSpeed: 1.0 },
  "single-dots": { type: "raw", name: "Single Dots",
    frames: ["⠁","⠂","⠄","⡀","⢀","⠠","⠐","⠈"], defaultSpeed: 1.0 },
  "single-bounce": { type: "raw", name: "Single Bounce",
    frames: ["⠁","⠂","⠄","⡀","⢀","⠠","⠐","⠈","⠐","⠠","⢀","⡀","⠄","⠂"], defaultSpeed: 1.0 },
  "single-fill": { type: "raw", name: "Single Fill",
    frames: ["⠁","⠃","⠇","⡇","⡏","⡟","⡿","⣿","⡿","⡟","⡏","⡇","⠇","⠃"], defaultSpeed: 1.0 },
  "single-sweep": { type: "raw", name: "Single Sweep",
    frames: ["⠁","⠉","⠘","⠰","⢠","⣀","⡄","⠆"], defaultSpeed: 1.0 },
  "half-helix":   { type: "raw", name: "Half Helix",
    frames: ["⣨⠿","⣬⠟","⣤⠟","⣴⠛","⣴⡛","⢶⣋","⢾⣉","⠾⣍","⠿⣅","⠻⣥","⠻⣦","⢛⣦","⢙⣶","⣙⡶","⣉⡷","⣩⠷"], defaultSpeed: 1.0 },
  "helix-core":   { type: "raw", name: "Helix Core",
    frames: ["⢠⡫","⡠⡻","⣔⠝","⢴⠋","⣮⠊","⡷⡁","⢕⡅","⢟⢄","⠫⣢","⠙⡦","⠑⣵","⢈⢾"], defaultSpeed: 1.0 },
  "helix-glow":   { type: "raw", name: "Helix Glow",
    frames: ["⠪⡱","⢣⢱","⢃⢕","⡑⢜","⡱⢸","⡡⢪","⡌⢪","⡜⡪","⡜⡱","⢔⠱","⢆⠕","⡎⡜","⡪⡘","⡣⢊","⡇⢎","⡕⢌","⡕⢡","⢕⢣","⢎⢣","⠎⡢"], defaultSpeed: 1.0 },
  "thought-helix": { type: "raw", name: "Thought Helix",
    frames: ["⢸⡇","⢰⡇","⡰⡃","⡸⢇","⢸⢇","⢜⢡","⢜⢣","⢜⡣","⠸⡢","⠪⡰","⢪⡕","⢘⡕","⢑⡕","⢑⡜","⢱⡎","⢨⡎","⢨⠎","⢸⡎","⢸⡇"], defaultSpeed: 1.0 },
  "pulse-ladder": { type: "raw", name: "Pulse Ladder",
    frames: ["⡀⢠","⡄⢀","⡆⠀","⠇⠀","⠋⠀","⠙⠀","⠸⠀","⢰⠀","⢠⡀","⢀⡄","⠀⡆","⠀⠇","⠀⠋","⠀⠙","⠀⠸","⠀⢰"], defaultSpeed: 1.3 },
  "core-spiral":  { type: "raw", name: "Core Spiral",
    frames: ["⠡⠄","⠩⠀","⠉⠁","⠈⠉","⠀⠙","⠀⠸","⠀⢰","⠀⣠","⢀⣀","⣀⡀","⣄⠀","⡆⠀","⠖⠀","⠒⠂","⠐⠆","⠠⠆"], defaultSpeed: 1.2 },
  "twin-orbit":   { type: "raw", name: "Twin Orbit",
    frames: ["⠷⠀","⠧⠄","⠫⠄","⠩⠅","⠨⠍","⠈⠏","⠀⠟","⠀⠾","⠀⢶","⠐⢲","⠐⣢","⢐⣂","⣐⡂","⣰⡀","⣴⠀","⡶⠀"], defaultSpeed: 1.0 },
  "infinity-run": { type: "raw", name: "Infinity Run",
    frames: ["⠐⠄","⠠⠀","⠀⢀","⡀⠠","⡀⠀","⠄⠐","⠀⠈","⠂⠈","⠁⠀","⠀⠂","⠐⠄","⠠⠀","⠀⢀","⡀⠠","⡀⠀","⠄⠐","⠀⠈","⠂⠈","⠁⠀","⠀⠂"], defaultSpeed: 1.0 },
  "radar-arc":    { type: "raw", name: "Radar Arc",
    frames: ["⠀⠰","⠀⠠","⠀⠤","⠀⡄","⠀⡀","⢀⡀","⢀⠀","⢠⠀","⠤⠀","⠄⠀","⠆⠀","⠂⠀","⠒⠀","⠘⠀","⠈⠀","⠈⠁","⠀⠁","⠀⠃","⠀⠒","⠀⠐"], defaultSpeed: 1.5 },
  "scan":        { type: "raw", name: "Scan",
    frames: ["⡇⠀","⣿⠀","⢸⡇","⠀⣿","⠀⢸","⠀⠀"], defaultSpeed: 1.0 },
  "sweep":       { type: "raw", name: "Sweep",
    frames: ["⡀⠀","⣀⠀","⣄⠀","⣆⠀","⣇⠀","⣿⠀","⢸⡇","⠀⣿","⠀⢸","⠀⢰","⠀⢠","⠀⣀","⠀⡀"], defaultSpeed: 1.0 },
  "agent-sweep": { type: "raw", name: "Agent Sweep",
    frames: ["⠁⠀","⠃⠀","⠇⠀","⡇⠀","⣿⠀","⢸⡇","⠀⣿","⠀⢸","⠀⠸","⠀⠘","⠀⠈","⠀⠐","⠀⠠","⠀⢀","⠀⡀","⢀⡀","⡀⠀","⠄⠀","⠂⠀"], defaultSpeed: 1.0 },
  "sound-bars":   { type: "raw", name: "Sound Bars",
    frames: ["⣰⣦","⣴⣤","⣶⣦","⣶⣄","⣶⣤","⣶⣰","⣦⣴","⣆⣶","⣦⣦","⣰⣦","⣴⣦","⣶⣆","⣶⣦","⣶⣴","⣦⣶","⣤⣶","⣰⣶"], defaultSpeed: 1.0 },
  "perimeter-spin-light": { type: "raw", name: "Perimeter Spin Light",
    frames: ["⠃⠀","⠉⠀","⠈⠁","⠀⠉","⠀⠘","⠀⠰","⠀⢠","⠀⣀","⢀⡀","⣀⠀","⡄⠀","⠆⠀"], defaultSpeed: 1.0 },
  "perimeter-spin": { type: "raw", name: "Perimeter Spin",
    frames: ["⠇⠀","⠋⠀","⠉⠁","⠈⠉","⠀⠙","⠀⠸","⠀⢰","⠀⣠","⢀⣀","⣀⡀","⣄⠀","⡆⠀"], defaultSpeed: 1.0 },
  "perimeter-spin-bold": { type: "raw", name: "Perimeter Spin Bold",
    frames: ["⡇⠀","⠏⠀","⠋⠁","⠉⠉","⠈⠙","⠀⠹","⠀⢸","⠀⣰","⢀⣠","⣀⣀","⣄⡀","⣆⠀"], defaultSpeed: 0.95 },
  "shuffle": { type: "raw", name: "Shuffle",
    frames: ["⢄","⢂","⢁","⡁","⡈","⡐","⡠"], defaultSpeed: 1.0 },
  "hangtime": { type: "raw", name: "Hangtime",
    frames: ["⢀⠀","⡀⠀","⠄⠀","⢂⠀","⡂⠀","⠅⠀","⢃⠀","⡃⠀","⠍⠀","⢋⠀","⡋⠀","⠍⠁","⢋⠁","⡋⠁","⠍⠉","⠋⠉","⠋⠉","⠉⠙","⠉⠙","⠉⠩","⠈⢙","⠈⡙","⢈⠩","⡀⢙","⠄⡙","⢂⠩","⡂⢘","⠅⡘","⢃⠨","⡃⢐","⠍⡐","⢋⠠","⡋⢀","⠍⡁","⢋⠁","⡋⠁","⠍⠉","⠋⠉","⠋⠉","⠉⠙","⠉⠙","⠉⠩","⠈⢙","⠈⡙","⠈⠩","⠀⢙","⠀⡙","⠀⠩","⠀⢘","⠀⡘","⠀⠨","⠀⢐","⠀⡐","⠀⠠","⠀⢀","⠀⡀"], defaultSpeed: 1.0 },
  "line-spin": { type: "raw", name: "Line Spin",
    frames: ["⠶⠶","⠒⠤","⠑⢄","⠘⡄","⢸⡇","⢠⠃","⡠⠊","⠤⠒"], defaultSpeed: 1.0 },
  "ray-spin": { type: "raw", name: "Ray Spin",
    frames: ["⠀⠶","⠀⢄","⢠⡄","⡠⠀","⠶⠀","⠑⠀","⠘⠃","⠀⠊"], defaultSpeed: 1.0 },
  "rotating-x":   { type: "raw", name: "Rotating X",
    frames: ["⠕⠪","⠚⡤","⠕⠪","⢤⠓"], defaultSpeed: 1.0 },
  "texture-flip":{ type: "raw", name: "Texture Flip",
    frames: ["⡪⡪","⢕⢕"], defaultSpeed: 1.0 },
  "neural-flicker": { type: "raw", name: "Neural Flicker",
    frames: ["⠁⠈","⠂⠐","⠄⠠","⡀⢀","⢄⡠","⢆⡰","⢇⣰","⣿⣿","⣰⢇","⡰⢆","⡠⢄","⢀⡀","⠠⠄","⠐⠂","⠈⠁"], defaultSpeed: 1.0 },
  "neural-flicker-chaos": { type: "raw", name: "Neural Flicker Chaos",
    frames: ["⠁⠈","⠂⠐","⠄⠠","⡀⢀","⢄⡠","⢆⡰","⢇⣰","⣿⣿","⣰⢇","⡰⢆","⡠⢄","⢀⡀","⠠⠄","⠐⠂","⠈⠁","⠈⠂","⠘⠄","⠸⡀","⢸⢀","⣸⠠","⣰⠐","⢠⠈","⡀⠘","⠄⠸","⠂⢸","⠁⣸","⠀⠰","⠈⠠","⠐⠄","⠂⠁","⠆⠈","⡆⠐","⣆⠠","⣇⢀","⢇⡀","⠇⡠","⠃⡰","⠁⣰","⠈⢠","⠐⡀","⠠⠄"], defaultSpeed: 1.0 },
  "neural-flicker-drift": { type: "raw", name: "Neural Flicker Drift",
    frames: ["⠁⠈","⠂⠐","⠄⠠","⡀⢀","⢄⡠","⢆⡰","⢇⣰","⣇⣸","⣰⢇","⡰⢆","⡠⢄","⢀⡀","⠠⠄","⠐⠂","⠈⠁","⠁⠂","⠃⠄","⠇⡀","⡇⢀","⣇⠠","⢇⠐","⠇⠈","⠃⠘","⠁⠸","⠂⢸","⠄⣸","⡀⢰","⢀⠠","⠠⠐","⠈⠄","⠘⡀","⠸⢀","⢸⠠","⣸⠐","⢰⠈","⠠⠘","⠐⠸","⠈⢸","⠐⣸","⠠⢰","⢀⠠"], defaultSpeed: 1.0 },
  "neural-flicker-thought": { type: "raw", name: "Neural Flicker Thought",
    frames: ["⠁⠈","⠂⠐","⠄⠠","⡀⢀","⢄⡠","⢆⡰","⢇⣰","⣇⣸","⢇⣰","⡰⢆","⡠⢄","⢀⡀","⠠⠄","⠐⠂","⠈⠁","⠈⠁","⠘⠂","⠸⠄","⢸⡀","⣸⢀","⢰⠠","⠠⠐","⠐⠈","⠘⠁","⠸⠂","⢸⠄","⣸⡀","⢰⢀","⠠⠠","⠂⠈","⠆⠐","⡆⠠","⣆⢀","⢆⡀","⠆⡠","⠂⡰","⠁⣰","⠈⢠","⠐⡀","⠠⠄","⢀⠂"], defaultSpeed: 1.0 },
  "neural-scatter": { type: "raw", name: "Neural Scatter",
    frames: ["⠁⠈","⠂⡐","⡄⠠","⠐⢀","⢄⠂","⠆⡰","⢇⠐","⠃⣰","⡠⠄","⠘⢆","⢀⡁","⠰⠂","⡂⠈","⠄⢠","⠈⡐","⠂⠠"], defaultSpeed: 1.15 },
  "neural-spike": { type: "raw", name: "Neural Spike",
    frames: ["⠁⠈","⠃⠐","⡂⠠","⠄⢀","⢄⠁","⠆⡠","⢂⠘","⠁⣰","⡀⠆","⠘⢄","⠠⡂","⠂⢀","⡁⠐","⠄⠈"], defaultSpeed: 1.2 },
  "neural-random-walk": { type: "raw", name: "Neural Random Walk",
    frames: ["⠁⠈","⠂⠐","⡄⠠","⢀⠂","⠆⡀","⠐⢄","⢂⠘","⠁⡰","⡠⠄","⠘⢂","⠄⡐","⠂⢀","⡁⠠","⠈⠆","⠐⡀","⢄⠁"], defaultSpeed: 1.1 },
  "neural-cross-spark": { type: "raw", name: "Neural Cross Spark",
    frames: ["⠁⠈","⠂⠐","⠄⠠","⡀⢀","⢄⡠","⠆⡰","⢂⡐","⠁⣰","⡠⠄","⠘⢆","⠐⢂","⠈⡁","⠠⠄","⠂⠐"], defaultSpeed: 1.0 },
  "neural-offset": { type: "raw", name: "Neural Offset",
    frames: ["⠁⠈","⡂⠐","⠄⢠","⢀⠂","⠆⡀","⠐⢄","⢂⠘","⠁⢰","⡠⠄","⠘⢂","⠄⡐","⠂⢀","⡁⠠","⠈⠆"], defaultSpeed: 1.15 },
  "neural-braid": { type: "raw", name: "Neural Braid",
    frames: ["⢨⠎","⢨⡎","⢠⡇","⢰⡃","⡰⡇","⡸⢅","⡜⢅","⡜⢇","⢜⢢","⢎⢢","⢎⢣","⢪⢱","⠣⡱","⠱⡸","⠑⡜","⢑⡜","⢘⡜","⢈⡎"], defaultSpeed: 1.0 },
  "thinking-pulse": { type: "raw", name: "Thinking Pulse",
    frames: ["⠁⠀","⠃⠀","⠇⠀","⡇⠀","⣇⠀","⣿⠀","⢸⡇","⠀⣿","⠀⣸","⠀⢸","⠀⠸","⠀⠘","⠀⠈","⠀⠐","⠀⠠","⠀⢀","⠀⡀","⢀⡀","⡀⠀","⠄⠀","⠂⠀"], defaultSpeed: 1.0 },
  "soft-thinking": { type: "raw", name: "Soft Thinking",
    frames: ["⠁⠀","⠂⠀","⠄⠀","⡀⠀","⢀⠀","⠀⢀","⠀⠠","⠀⠐","⠀⠈","⠀⠐","⠀⠠","⠀⢀","⢀⠀","⡀⠀","⠄⠀","⠂⠀"], defaultSpeed: 1.0 },
  "deep-thought": { type: "raw", name: "Deep Thought",
    frames: ["⠁⠀","⠃⠀","⠇⠀","⡇⠀","⣇⠀","⣧⠀","⣿⠀","⣿⡇","⢸⣿","⠀⣿","⠀⣼","⠀⣸","⠀⢰","⠀⠠","⠀⠐","⠀⠈","⠀⠐","⠀⠠","⠀⢀","⠀⡀","⢀⡀","⡀⠀","⠄⠀","⠂⠀"], defaultSpeed: 1.0 },
  "signal-search": { type: "raw", name: "Signal Search",
    frames: ["⠁⠀","⠃⠀","⠇⠀","⡇⠀","⡇⠁","⡇⠃","⡇⠇","⡇⡇","⠇⡇","⠃⡇","⠁⡇","⠀⡇","⠀⠇","⠀⠃","⠀⠁"], defaultSpeed: 1.0 },
  "binary-thought": { type: "raw", name: "Binary Thought",
    frames: ["⠁⠈","⠃⠘","⠇⠸","⡇⢸","⣇⣸","⡇⢸","⠇⠸","⠃⠘","⠁⠈","⠂⠐","⠆⠰","⠄⠠","⠂⠐"], defaultSpeed: 1.0 },
  "center-spark": { type: "raw", name: "Center Spark",
    frames: ["⠲⣆","⠲⢦","⠳⠦","⠹⠦","⠹⠶","⠸⠗","⡸⠟","⡰⠏","⣰⠎","⣴⡎","⢴⡆","⠶⣆"], defaultSpeed: 1.0 },
  "synapse-wave": { type: "raw", name: "Synapse Wave",
    frames: ["⣀⠝","⢄⠕","⢐⠕","⣠⠋","⡤⠊","⡢⠊","⢨⡊","⢴⠁","⢖⠁","⢕⢁","⠪⡄","⠺⡀","⠫⣀","⠑⢤","⠑⢔","⢑⢅","⠈⡦","⠈⡲","⡈⡪","⢨⠔"], defaultSpeed: 1.0 },
  "inner-current": { type: "raw", name: "Inner Current",
    frames: ["⢰⠇","⢰⠃","⢠⠃","⢠⠇","⠸⡇","⠸⡅","⠸⡁","⢸⡄","⢸⡅","⢸⡇","⢈⠇","⢈⡇","⢈⡆"], defaultSpeed: 1.0 },
  "bouncing-block": { type: "raw", name: "Bouncing Block",
    frames: ["⡇⠀","⣇⠀","⣿⠀","⢸⡇","⠀⣿","⠀⣸","⠀⢸","⠀⣸","⠀⣿","⢸⡇","⣿⠀","⣇⠀"], defaultSpeed: 1.0 },
  "face":         { type: "raw", name: "Smiley Face",
    frames: ["⣀⣀","⣁⣈","⢅⡨","⢄⡨","⢅⡨","⣁⣈"], defaultSpeed: 1.0 },
  "snake-crawl": { type: "raw", name: "Snake Crawl",
    frames: ["⠉⠉","⠉⠁","⠉⠁","⠉⠉","⠈⠙","⠀⠛","⠐⠚","⠒⠒","⠖⠂","⠶⠀","⠦⠄","⠤⠤","⠠⢤","⠀⣤","⢀⣠","⣀⣀","⣀⡀","⣀⡀","⣀⣀","⢀⣠","⠀⣤","⠠⢤","⠤⠤","⠦⠄","⠶⠀","⠖⠂","⠒⠒","⠐⠚","⠀⠛","⠈⠙"], defaultSpeed: 1.0 },
  "snake-loop": { type: "raw", name: "Snake Loop",
    frames: ["⠉⠉","⠈⠙","⠀⠛","⠐⠚","⠒⠒","⠖⠂","⠶⠀","⠦⠄","⠤⠤","⠠⢤","⠀⣤","⢀⣠","⣀⣀","⣄⡀","⣤⠀","⡤⠄","⠤⠤","⠠⠴","⠀⠶","⠐⠲","⠒⠒","⠓⠂","⠛⠀","⠋⠁"], defaultSpeed: 1.0 },
  "circle": { type: "raw", name: "Circle",
    frames: [" ",".","o","O","@",""], defaultSpeed: 1.0 },
  "square": { type: "raw", name: "Square",
    frames: ["□","■"], defaultSpeed: 1.0 },
  "twinkle": { type: "raw", name: "Twinkle",
    frames: ["+","×"], defaultSpeed: 1.0 },
  "corners": { type: "raw", name: "Corners",
    frames: ["◢","◣","◤","◥"], defaultSpeed: 1.0 },
  "growth": { type: "raw", name: "Growth",
    frames: ["▁","▃","▄","▅","▆","▇","▆","▅","▄","▃"], defaultSpeed: 1.0 },
};

export const PATTERN_KEYS = Object.keys(PATTERNS);
